In [1]:
print("""
@Description: Creating Tensor
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-04-30 13:17:12
""")


@Description: Creating Tensor
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-04-30 13:17:12



In [2]:
import torch

In [3]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [4]:
torch.empty(3, 5)

tensor([[-7.0356e+13,  6.5020e-43, -7.0356e+13,  6.5020e-43, -7.0356e+13],
        [ 6.5020e-43, -7.0356e+13,  6.5020e-43, -7.0356e+13,  6.5020e-43],
        [-7.0356e+13,  6.5020e-43, -7.0356e+13,  6.5020e-43, -7.0356e+13]])

In [5]:
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [10]:
torch.logspace(0, 10, 5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
x = torch.full((3, 5), fill_value=7)

In [21]:
torch.save(x, 'x.pt')

In [26]:
y = torch.load('x.pt')

In [27]:
y == x

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

## Tensor Attributes

In [31]:
x.dtype, x.device, x.shape, x.ndim, x.requires_grad, 
from torch import Tensor

In [40]:
def describe(x: Tensor):
    print("tensor dtype: \t{}".format(x.dtype))
    print("tensor device: \t{}".format(x.device))
    print("tensor shape: \t{}".format(x.shape))
    print("tensor ndim: \t{}".format(x.ndim))
    print("tensor requires_grad: \t{}".format(x.requires_grad))
    print("tensor grad: \t{}".format(x.grad))
    print("tensor grad_fn: \t{}".format(x.grad_fn))
    print("tensor layout: \t{}".format(x.layout))

In [41]:
describe(x)

tensor dtype: 	torch.int64
tensor device: 	cpu
tensor shape: 	torch.Size([3, 5])
tensor ndim: 	2
tensor requires_grad: 	False
tensor grad: 	None
tensor grad_fn: 	None
tensor layout: 	torch.strided


In [45]:
x.is_sparse, x.is_quantized, x.is_leaf

(False, False, True)

## Data Types

In [46]:
w = torch.tensor([1, 2, 3])

In [49]:
w.int()
# w remains a float32 after the cast

tensor([1, 2, 3], dtype=torch.int32)

In [50]:
w = w.int()

In [51]:
w = w.to(torch.float64)

In [52]:
w = w.to(dtype=torch.float64)

In [53]:
x = torch.tensor([1, 2, 3], dtype=torch.int32)

In [54]:
y = torch.tensor([1, 2, 3], dtype=torch.float32)

In [55]:
z = x + y

In [56]:
z.dtype

torch.float32

## Creating Tensors from Random Samples

In [57]:
torch.rand(3, 7)

tensor([[0.0273, 0.4139, 0.5866, 0.7222, 0.7708, 0.5917, 0.1391],
        [0.2248, 0.8716, 0.9280, 0.7363, 0.6386, 0.3564, 0.8508],
        [0.6567, 0.9498, 0.1083, 0.3601, 0.5999, 0.1163, 0.5361]])

In [58]:
torch.randn(3, 7)

tensor([[-0.5396,  0.5324,  0.6380,  0.8067, -0.0182,  1.9867,  0.0840],
        [-0.5296, -0.7410,  0.2220,  0.4367,  2.0288,  0.7373,  1.5183],
        [-1.3384,  0.2583, -0.6638,  0.8061,  0.6036, -1.6804, -1.6310]])

In [63]:
torch.normal(0, 1, (3, 7))

tensor([[-0.8573,  0.2652,  1.2530,  0.0171,  0.0868,  0.8078, -0.6954],
        [-1.5183, -1.4723,  0.5419, -0.7247,  0.3592, -0.5996, -0.7205],
        [ 0.6489,  1.0577, -0.3277,  0.0113,  0.0716, -0.5720,  0.5393]])

In [64]:
torch.randint(1, 10, (3, 7))

tensor([[8, 3, 7, 9, 1, 1, 5],
        [5, 4, 4, 2, 3, 1, 9],
        [1, 9, 8, 4, 4, 3, 8]])

In [66]:
torch.randperm(10)

tensor([2, 9, 8, 5, 6, 3, 1, 4, 0, 7])

In [70]:
a = torch.rand(3, 7)
torch.bernoulli(a)

tensor([[0., 1., 0., 1., 0., 1., 1.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 1., 0., 0., 1.]])

In [73]:
weights = torch.Tensor([
    [0, 0.3, 0.7], 
    [0.3, 0.7, 0]
])
torch.multinomial(weights, 2)

tensor([[1, 2],
        [1, 0]])