In [1]:
print("""
@Description: TensorFlow 入门
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-26 20:06:18
""")


@Description: TensorFlow 入门
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-26 20:06:18



In [2]:
import tensorflow as tf

In [5]:
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [7]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [9]:
x = tf.random.normal(shape=(3, 1), mean=0, stddev=1.)
print(x)

tf.Tensor(
[[0.32155094]
 [0.05929212]
 [0.61516327]], shape=(3, 1), dtype=float32)


In [10]:
x = tf.random.uniform(shape=(3, 1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.46094954]
 [0.7206944 ]
 [0.7344996 ]], shape=(3, 1), dtype=float32)


In [12]:
import numpy as np
x = np.ones(shape=(2, 2))
x

array([[1., 1.],
       [1., 1.]])

In [13]:
x[0, 0] = 999

In [14]:
x

array([[999.,   1.],
       [  1.,   1.]])

In [20]:
x = tf.ones(shape=(2, 2))
try:
    x[0, 0] = 999
except TypeError:
    print('TensorFlow 张量是不可赋值的')

TensorFlow 张量是不可赋值的


In [22]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.00401507],
       [ 0.677259  ],
       [-0.6407788 ]], dtype=float32)>


In [23]:
v.assign(tf.ones(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [24]:
v[0, 0].assign(3.0)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [26]:
v.assign_add(tf.ones(shape=(3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

### 张量运算：用 TensorFlow 进行数学运算

In [29]:
a = tf.ones(shape=(2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d

### 重温 GradientTape API

In [35]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [36]:
time = tf.Variable(0.0)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
print(acceleration)

tf.Tensor(9.8, shape=(), dtype=float32)
