In [2]:
print("""
@Description: 自动微分
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-04-25 22:16:57
""")


@Description: 自动微分
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-04-25 22:16:57



In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4 * x

tensor([True, True, True, True])

In [9]:
y = x.sum()
y.backward()
x.grad

tensor([ 1.,  5.,  9., 13.])

在默认情况下，PyTorch会累积梯度，我们需要清除之前的值

In [10]:
y = x.sum()
x.grad.zero_()
y.backward()
x.grad

tensor([1., 1., 1., 1.])