In [1]:
print("""
@Description: NumPy 互操作性
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-08-18 09:49:11
""")


@Description: NumPy 互操作性
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-08-18 09:49:11



In [7]:
import torch

In [8]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [9]:
points_np[0, 0] = 999
points

tensor([[999.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]])

有趣的是，返回的数组与张量存储共享相同的底层缓冲区。这意味着，只要数据位于 CPU 上的RAM 中，就可以有效地执行 numpy()方法，而且基本上不需要任何开销，还意味着修改 NumPy 数将导致原始张量的变化。如果张量是在 GPU 上存储的，PyTorch 将把张量的内容复制到 CPU 上分的 NumPy 数组中。

In [10]:
points = torch.from_numpy(points_np)
points

tensor([[999.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]])