In [1]:
print("""
@Description: 练习题
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-08-18 14:09:13
""")


@Description: 练习题
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-08-18 14:09:13



In [2]:
import torch

In [3]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.size()

torch.Size([9])

In [5]:
a.storage_offset()

0

In [6]:
a.stride()

(1,)

In [7]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
id(a.storage()), id(b.storage())

C:\Users\JPL-JUNO\AppData\Local\Temp\ipykernel_17744\1446716103.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(a.storage()), id(b.storage())


(1950797791392, 1951215794352)

In [9]:
assert id(a.storage().data_ptr()) == id(b.storage().data_ptr())

In [11]:
torch.sqrt

<function torch._VariableFunctionsClass.sqrt>

In [12]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [13]:
a.square()

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64])